#!/bin/bash

for ARTISTPATH in MUSIC/*; do
  ARTIST=$(basename "$ARTISTPATH")
  for ALBUMPATH in "$ARTISTPATH"/*; do
    ALBUM=$(basename "$ALBUMPATH")
    find  "MUSIC/$ARTIST/$ALBUM" | grep -i -E '\.(flac|mp3)$' | sort | awk -v ORS='\r\n' 1 - >"$ARTIST - $ALBUM.m3u"
    echo "Created playlist $ARTIST - $ALBUM.m3u"
  done
done
